export default [
    {
        'id': 1,
        'imgName': 'venice2.jpg',
        'country': 'ITALY',
        'googleMapsLink': 'https://goo.gl/maps/wFtMKPNp5gLaMid66',
        'location': 'Venice',
        'startDate': Date(7, 7, 2021),
        'endDate': Date(12, 7, 2021),
        'description': 'Venice is a city in northeastern Italy and the capital of the Veneto region. It is built on a group of 118 small islands that are separated by canals and linked by over 400 bridges. Over there I learned a lot about architecture and Design Thinking and managed to persuade locals to let me stay for a night at their place.',
    },
    {
        'id': 2,
        'imgName': 'barcelona.jpg',
        'country': 'SPAIN',
        'googleMapsLink': 'https://goo.gl/maps/xn3FWx5GAGjvGmjS8',
        'location': 'Sagrada Família',
        'startDate': Date(7, 4, 2019),
        'endDate': Date(12, 4, 2019),
        'description': 'The Basílica i Temple Expiatori de la Sagrada Família is a large unfinished church building in the Eixample district of Barcelona, Catalonia, Spain, and is currently the largest unfinished Roman Catholic church. Designed by the Catalan architect Antoni Gaudí (1852 – 1926), his work on Sagrada Família is part of a UNESCO World Heritage Site.',
    },
    {
        'id': 3,
        'imgName': 'budapest.jpg',
        'country': 'HUNGARY',
        'googleMapsLink': 'https://goo.gl/maps/7QPzC5y6U3vdEimp8',
        'location': 'Budapest',
        'startDate': Date(12, 10, 2021),
        'endDate': Date(16, 10, 2021),
        'description': 'Budapest is the capital and most populous city of Hungary. It is the ninth-largest city in the European Union by population within city limits and the second-largest city on Danube river. I went there with Anna for a weekend trip and we managed to arrive at the best possible time: during the annual Trash Festival. The locals had put out all of their excess belongings on the street for exactly one day, and anyone can take anything they find.',
    },
    {
        'id': 4,
        'imgName': 'valletta.jpg',
        'country': 'MALTA',
        'googleMapsLink': 'https://goo.gl/maps/suKrDzAA6qZX34rJ6',
        'location': 'Valletta',
        'startDate': Date(3, 7, 2021),
        'endDate': Date(7, 7, 2021),
        'description': 'Valletta is the administrative unit and capital of Malta. Located on the main island, between Marsamxett Harbour to the west and the Grand Harbour to the east, it also holds the title of being the southernmost European capital. Ask me about the time I accidentally went to church because I wanted to charge my phone.',
    }
]